package atom;

@:realPath("atom.Atom") @:native("Atom") extern class Atom {
	var clipboard : Dynamic;
	var commands : Dynamic;
	var config : Dynamic;
	var contextMenu : Dynamic;
	var deserializers : Dynamic;
	var grammars : Dynamic;
	var keymaps : Dynamic;
	var menu : Dynamic;
	var packages : Dynamic;
	var project : Dynamic;
	var styles : Dynamic;
	var themes : Dynamic;
	var tooltips : Dynamic;
	var views : Dynamic;
	var workspace : Dynamic;
	function beep() : Void;
	function center() : Void;
	function close() : Void;
	function confirm(options : Dynamic<Dynamic>) : Float;
	function executeJavaScriptInDevTools() : Void;
	function focus() : Void;
	function getPosition() : Dynamic<Dynamic>;
	function getSize() : Dynamic<Dynamic>;
	function getVersion() : String;
	function getWindowLoadTime() : Float;
	function hide() : Void;
	function inDevMode() : Void;
	function inSafeMode() : Void;
	function inSpecMode() : Void;
	function isFullScreen() : Void;
	function isMaximixed() : Bool;
	function isReleasedVersion() : Void;
	function onDidBeep(callback : haxe.Function) : Disposable;
	function onDidThrowError(callback : haxe.Function) : Disposable;
	function onWillThrowError(callback : haxe.Function) : Disposable;
	function open(options : Dynamic<Dynamic>) : Void;
	function openDevTools() : Void;
	function pickFolder(callback : haxe.Function) : Void;
	function reload() : Void;
	function setFullScreen() : Void;
	function setPosition(x : Float, y : Float) : Void;
	function setSize(width : Float, height : Float) : Void;
	function show() : Void;
	function toggleDevTools() : Void;
	function toggleFullScreen() : Void;
}
