package atom;

@:realPath("atom.Cursor") @:native("Cursor") extern class Cursor {
	function clearAutoscroll() : Void;
	function clearSelection() : Void;
	function compare(otherCursor : Cursor) : Void;
	function getBeginningOfCurrentWordBufferPosition(options : Dynamic<Dynamic>) : Range;
	function getBeginningOfNextWordBufferPosition(options : Dynamic<Dynamic>) : Range;
	function getBufferColumn() : Dynamic;
	function getBufferPosition() : Dynamic;
	function getBufferRow() : Void;
	function getCurrentBufferLine() : Dynamic;
	function getCurrentLineBufferRange(options : Dynamic<Dynamic>) : Dynamic;
	function getCurrentParagraphBufferRange() : Range;
	function getCurrentWordBufferRange(options : Dynamic<Dynamic>) : Dynamic;
	function getCurrentWordPrefix() : Dynamic;
	function getEndOfCurrentWordBufferPosition(options : Dynamic<Dynamic>) : Range;
	function getIndentLevel() : Dynamic;
	function getMarker() : Marker;
	function getNextWordBoundaryBufferPosition(options : Dynamic<Dynamic>) : Dynamic;
	function getPreviousWordBoundaryBufferPosition(options : Dynamic<Dynamic>) : Dynamic;
	function getScopeDescriptor() : ScopeDescriptor;
	function getScreenColumn() : Dynamic;
	function getScreenPosition() : Dynamic;
	function getScreenRow() : Dynamic;
	function hasPrecedingCharactersOnLine() : Dynamic;
	function isAtBeginningOfLine() : Dynamic;
	function isAtEndOfLine() : Dynamic;
	function isBetweenWordAndNonWord() : Dynamic;
	function isInsideWord(options : Dynamic<Dynamic>) : Dynamic;
	function isLastCursor() : Bool;
	function isSurroundedByWhitespace() : Bool;
	function isVisible() : Dynamic;
	function moveDown(rowCount : Float, options : Dynamic<Dynamic>) : Void;
	function moveLeft(columnCount : Float, options : Dynamic<Dynamic>) : Void;
	function moveRight(columnCount : Float, options : Dynamic<Dynamic>) : Void;
	function moveToBeginningOfLine() : Void;
	function moveToBeginningOfNextParagraph() : Void;
	function moveToBeginningOfNextWord() : Void;
	function moveToBeginningOfPreviousParagraph() : Void;
	function moveToBeginningOfScreenLine() : Void;
	function moveToBeginningOfWord() : Void;
	function moveToBottom() : Void;
	function moveToEndOfLine() : Void;
	function moveToEndOfScreenLine() : Void;
	function moveToEndOfWord() : Void;
	function moveToFirstCharacterOfLine() : Void;
	function moveToNextWordBoundary() : Void;
	function moveToPreviousWordBoundary() : Void;
	function moveToTop() : Void;
	function moveUp(rowCount : Float, options : Dynamic<Dynamic>) : Void;
	function onDidChangePosition(callback : haxe.Function) : Disposable;
	function onDidChangeVisibility(callback : haxe.Function) : Disposable;
	function onDidDestroy(callback : haxe.Function) : Disposable;
	function setBufferPosition(bufferPosition : Array<Dynamic>, options : Dynamic<Dynamic>) : Void;
	function setScreenPosition(screenPosition : Array<Dynamic>, options : Dynamic<Dynamic>) : Void;
	function setVisible() : Void;
	function skipLeadingWhitespace() : Void;
	function wordRegExp(options : Dynamic<Dynamic>) : js.RegExp;
}
