package atom;

@:realPath("atom.Workspace") @:native("Workspace") extern class Workspace {
	function activateNextPane() : Void;
	function activatePreviousPane() : Void;
	function addBottomPanel(options : Dynamic<Dynamic>) : Panel;
	function addLeftPanel(options : Dynamic<Dynamic>) : Panel;
	function addModalPanel(options : Dynamic<Dynamic>) : Panel;
	function addOpener(opener : haxe.Function) : Disposable;
	function addRightPanel(options : Dynamic<Dynamic>) : Panel;
	function addTopPanel(options : Dynamic<Dynamic>) : Panel;
	function getActivePane() : Pane;
	function getActivePaneItem() : Dynamic<Dynamic>;
	function getActiveTextEditor() : TextEditor;
	function getBottomPanels() : Void;
	function getLeftPanels() : Void;
	function getModalPanels() : Void;
	function getPaneItems() : Array<Dynamic>;
	function getPanes() : Array<Dynamic>;
	function getRightPanels() : Void;
	function getTextEditors() : Array<Dynamic>;
	function getTopPanels() : Void;
	function observeActivePane(callback : haxe.Function) : Disposable;
	function observeActivePaneItem(callback : haxe.Function) : Disposable;
	function observePaneItems(callback : haxe.Function) : Disposable;
	function observePanes(callback : haxe.Function) : Disposable;
	function observeTextEditors(callback : haxe.Function) : Disposable;
	function onDidAddPane(callback : haxe.Function) : Disposable;
	function onDidAddPaneItem(callback : haxe.Function) : Disposable;
	function onDidAddTextEditor(callback : haxe.Function) : Disposable;
	function onDidChangeActivePane(callback : haxe.Function) : Disposable;
	function onDidChangeActivePaneItem(callback : haxe.Function) : Disposable;
	function onDidDestroyPane(callback : haxe.Function) : Disposable;
	function onDidDestroyPaneItem(callback : haxe.Function) : Disposable;
	function onDidOpen(callback : haxe.Function) : Disposable;
	function onWillDestroyPaneItem(callback : haxe.Function) : Disposable;
	function open(uri : String, options : Dynamic<Dynamic>) : TextEditor;
	function paneForItem(item : Dynamic) : Pane;
	function paneForURI(uri : String) : Pane;
	function panelForItem(item : Dynamic) : Dynamic;
	function reopenItem() : Dynamic;
	function replace(regex : js.RegExp, replacementText : Dynamic, filePaths : Dynamic, iterator : haxe.Function) : Dynamic;
	function scan(regex : js.RegExp, options : Dynamic<Dynamic>, iterator : haxe.Function) : Dynamic;
}
