package atom;
@:native("Cursor") extern class Cursor {
	function onDidChangePosition(callback:haxe.Constraints.Function):atom.Disposable;
	function onDidDestroy(callback:haxe.Constraints.Function):atom.Disposable;
	function onDidChangeVisibility(callback:haxe.Constraints.Function):atom.Disposable;
	function setScreenPosition(screenPosition:Array<Dynamic>, options:Dynamic<Dynamic>):Void;
	function getScreenPosition():Dynamic;
	function setBufferPosition(bufferPosition:Array<Dynamic>, options:Dynamic<Dynamic>):Void;
	function getBufferPosition():Dynamic;
	function getScreenRow():Dynamic;
	function getScreenColumn():Dynamic;
	function getBufferRow():Void;
	function getBufferColumn():Dynamic;
	function getCurrentBufferLine():Dynamic;
	function isAtBeginningOfLine():Dynamic;
	function isAtEndOfLine():Dynamic;
	function getMarker():atom.Marker;
	function isSurroundedByWhitespace():Bool;
	function isBetweenWordAndNonWord():Dynamic;
	function isInsideWord(options:Dynamic<Dynamic>):Dynamic;
	function getIndentLevel():Dynamic;
	function getScopeDescriptor():atom.ScopeDescriptor;
	function hasPrecedingCharactersOnLine():Dynamic;
	function isLastCursor():Bool;
	function moveUp(rowCount:Float, options:Dynamic<Dynamic>):Void;
	function moveDown(rowCount:Float, options:Dynamic<Dynamic>):Void;
	function moveLeft(columnCount:Float, options:Dynamic<Dynamic>):Void;
	function moveRight(columnCount:Float, options:Dynamic<Dynamic>):Void;
	function moveToTop():Void;
	function moveToBottom():Void;
	function moveToBeginningOfScreenLine():Void;
	function moveToBeginningOfLine():Void;
	function moveToFirstCharacterOfLine():Void;
	function moveToEndOfScreenLine():Void;
	function moveToEndOfLine():Void;
	function moveToBeginningOfWord():Void;
	function moveToEndOfWord():Void;
	function moveToBeginningOfNextWord():Void;
	function moveToPreviousWordBoundary():Void;
	function moveToNextWordBoundary():Void;
	function skipLeadingWhitespace():Void;
	function moveToBeginningOfNextParagraph():Void;
	function moveToBeginningOfPreviousParagraph():Void;
	function getPreviousWordBoundaryBufferPosition(options:Dynamic<Dynamic>):Dynamic;
	function getNextWordBoundaryBufferPosition(options:Dynamic<Dynamic>):Dynamic;
	function getBeginningOfCurrentWordBufferPosition(options:Dynamic<Dynamic>):atom.Range;
	function getEndOfCurrentWordBufferPosition(options:Dynamic<Dynamic>):atom.Range;
	function getBeginningOfNextWordBufferPosition(options:Dynamic<Dynamic>):atom.Range;
	function getCurrentWordBufferRange(options:Dynamic<Dynamic>):Dynamic;
	function getCurrentLineBufferRange(options:Dynamic<Dynamic>):Dynamic;
	function getCurrentParagraphBufferRange():atom.Range;
	function getCurrentWordPrefix():Dynamic;
	function setVisible():Void;
	function isVisible():Dynamic;
	function compare(otherCursor:atom.Cursor):Void;
	function clearAutoscroll():Void;
	function clearSelection():Void;
	function wordRegExp(options:Dynamic<Dynamic>):js.RegExp;
}